### ISSUE TITLE
[BUG] Got an error while running challenge_examples.py

### ISSUE THREAD

**Issue by ruanqizhen** [osmlab/maproulette-python-client#96]
Run challenge_examples.py, go the following error:

```
Traceback (most recent call last):
  File "C:\test\test_osc\challenge_examples.py", line 65, in <module>
    print(json.dumps(api.add_tasks_to_challenge(data, challenge_id)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ruanqizhen\AppData\Local\miniconda3\envs\test\Lib\site-packages\maproulette\api\challenge.py", line 276, in add_tasks_to_challenge
    response = self.put(
               ^^^^^^^^^
  File "C:\Users\ruanqizhen\AppData\Local\miniconda3\envs\test\Lib\site-packages\maproulette\api\maproulette_server.py", line 156, in put
    raise InvalidJsonError(
maproulette.api.errors.InvalidJsonError: {'status': 400, 'message': 'Invalid JSON payload.'}
```

I'm using the same JSON data (Example_Geometry.geojson) in the example.  

Any idea how to fix this problem?

**Comment by mattmanley** [comment]
@ruanqizhen I just tried this with a new challenge of my own. I was not getting the same error as you. The task was uploaded with no problem. Maybe leave out the overpass bit prior to adding the tasks to the challenge. Just try adding them to a new challenge that has not been configured to use overpass.

**Comment by ruanqizhen** [comment]
I found the problem: I passed a challenge ID with the wrong data type, it should have been an integer.
